### ISSUE TITLE
Empty loginProvider no longer supported. 

### ISSUE THREAD

**Issue by yfeleke** [Web3Auth/web3auth-react-native-sdk#56]
[Docs](https://web3auth.io/docs/sdk/react-native/usage) clearly state that you can leave out loginProvider and this allows the user to pick a login provider. As of last week, type definitions state loginProvider is required and the webpage requests setting loginProvider. 

The functionality was important for my application because it allowed users to pick their least worrisome sign in method. If this functionality is removed, how can we support specifying all LOGIN_TYPES or provide an array ?

**Comment by yfeleke** [comment]
@chaitanyapotti  Saw you commit "Make loginProvider Mandotory" https://github.com/Web3Auth/web3auth-react-native-sdk/commit/9b705a6d5bd067dc301e4fa88bde3735ff040166

**Comment by yfeleke** [comment]
Bump

**Comment by chaitanyapotti** [comment]
Hello..
apologies for the delayed response.
the docs are under a revamp and aren't updated yet.
We've made the loginProvider parameter as mandatory because of complaints received from play store and app store.
Both of them have informed us that all login(OAuth) buttons have to be present within the app itself. So, we had to make this change.!
